<?php

declare(strict_types=1);

namespace App\Services\EmailTemplate;

use App\Events\EmailTemplate\EmailTemplatePublished;
use App\Events\EmailTemplate\EmailTemplateSaved;
use App\Models\EmailTemplate\EmailTemplate;
use Illuminate\Support\Facades\DB;

class EmailTemplateService
{
    /**
     * Save drafts for an email template.
     *
     * @param  array  $translations  Array of ['locale' => ['subject' => ..., 'html_content' => ...]]
     */
    public function saveDraft(EmailTemplate $template, array $translations): void
    {
        DB::transaction(function () use ($template, $translations) {
            foreach ($translations as $locale => $data) {
                // Prepare draft data
                $draftData = [
                    'draft_subject' => $data['subject'] ?? null,
                    'draft_html_content' => $data['html_content'] ?? null,
                    // text_content will be generated by listener
                    'draft_preheader' => $data['preheader'] ?? null,
                ];

                $template->translations()->updateOrCreate(
                    ['locale' => $locale],
                    $draftData,
                );
            }

            // Dispatch event to trigger listeners (e.g., text generation)
            EmailTemplateSaved::dispatch($template);
        });
    }

    /**
     * Publish an email template.
     */
    public function publish(EmailTemplate $template): void
    {
        DB::transaction(function () use ($template) {
            // Logic moved to listener via event
            EmailTemplatePublished::dispatch($template);
        });
    }

    /**
     * Restore published content to draft (discard draft changes).
     */
    public function restoreToDraft(EmailTemplate $template): void
    {
        DB::transaction(function () use ($template) {
            foreach ($template->translations as $translation) {
                $translation->update([
                    'draft_subject' => $translation->subject,
                    'draft_html_content' => $translation->html_content,
                    'draft_text_content' => $translation->text_content,
                    'draft_preheader' => $translation->preheader,
                ]);
            }

            // Trigger save event to ensure any consistency checks run
            EmailTemplateSaved::dispatch($template);
        });
    }
}
